// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_expmAction_RCPPEXPORTS_H_GEN_
#define RCPP_expmAction_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace expmAction {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("expmAction", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("expmAction", "_expmAction_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in expmAction");
            }
        }
    }

    inline arma::mat cpp_v_exp_Q_t(const arma::rowvec& v, const arma::sp_mat& Q, double t = 1, double tolerance = 1.0e-12) {
        typedef SEXP(*Ptr_cpp_v_exp_Q_t)(SEXP,SEXP,SEXP,SEXP);
        static Ptr_cpp_v_exp_Q_t p_cpp_v_exp_Q_t = NULL;
        if (p_cpp_v_exp_Q_t == NULL) {
            validateSignature("arma::mat(*cpp_v_exp_Q_t)(const arma::rowvec&,const arma::sp_mat&,double,double)");
            p_cpp_v_exp_Q_t = (Ptr_cpp_v_exp_Q_t)R_GetCCallable("expmAction", "_expmAction_cpp_v_exp_Q_t");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_cpp_v_exp_Q_t(Shield<SEXP>(Rcpp::wrap(v)), Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(t)), Shield<SEXP>(Rcpp::wrap(tolerance)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

}

#endif // RCPP_expmAction_RCPPEXPORTS_H_GEN_
