// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_expmAction_RCPPEXPORTS_H_GEN_
#define RCPP_expmAction_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace expmAction {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("expmAction", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("expmAction", "_expmAction_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in expmAction");
            }
        }
    }

    inline Rcpp::List cpp_tune_uniformization(const arma::sp_mat& Q, double tolerance = 1e-12) {
        typedef SEXP(*Ptr_cpp_tune_uniformization)(SEXP,SEXP);
        static Ptr_cpp_tune_uniformization p_cpp_tune_uniformization = NULL;
        if (p_cpp_tune_uniformization == NULL) {
            validateSignature("Rcpp::List(*cpp_tune_uniformization)(const arma::sp_mat&,double)");
            p_cpp_tune_uniformization = (Ptr_cpp_tune_uniformization)R_GetCCallable("expmAction", "_expmAction_cpp_tune_uniformization");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_cpp_tune_uniformization(Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(tolerance)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::List >(rcpp_result_gen);
    }

    inline arma::sp_mat cpp_execute_uniformization(const arma::sp_mat& Q, const arma::sp_mat& x, int s, int m, double alpha, double tolerance = 1e-12) {
        typedef SEXP(*Ptr_cpp_execute_uniformization)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_cpp_execute_uniformization p_cpp_execute_uniformization = NULL;
        if (p_cpp_execute_uniformization == NULL) {
            validateSignature("arma::sp_mat(*cpp_execute_uniformization)(const arma::sp_mat&,const arma::sp_mat&,int,int,double,double)");
            p_cpp_execute_uniformization = (Ptr_cpp_execute_uniformization)R_GetCCallable("expmAction", "_expmAction_cpp_execute_uniformization");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_cpp_execute_uniformization(Shield<SEXP>(Rcpp::wrap(Q)), Shield<SEXP>(Rcpp::wrap(x)), Shield<SEXP>(Rcpp::wrap(s)), Shield<SEXP>(Rcpp::wrap(m)), Shield<SEXP>(Rcpp::wrap(alpha)), Shield<SEXP>(Rcpp::wrap(tolerance)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::sp_mat >(rcpp_result_gen);
    }

}

#endif // RCPP_expmAction_RCPPEXPORTS_H_GEN_
