// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/expmAction.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_v_exp_Q_t
arma::mat cpp_v_exp_Q_t(const arma::rowvec& v, const arma::sp_mat& Q, double t, double tolerance);
static SEXP _expmAction_cpp_v_exp_Q_t_try(SEXP vSEXP, SEXP QSEXP, SEXP tSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_v_exp_Q_t(v, Q, t, tolerance));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _expmAction_cpp_v_exp_Q_t(SEXP vSEXP, SEXP QSEXP, SEXP tSEXP, SEXP toleranceSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_expmAction_cpp_v_exp_Q_t_try(vSEXP, QSEXP, tSEXP, toleranceSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        (Rf_error)("%s", CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _expmAction_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::mat(*cpp_v_exp_Q_t)(const arma::rowvec&,const arma::sp_mat&,double,double)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _expmAction_RcppExport_registerCCallable() { 
    R_RegisterCCallable("expmAction", "_expmAction_cpp_v_exp_Q_t", (DL_FUNC)_expmAction_cpp_v_exp_Q_t_try);
    R_RegisterCCallable("expmAction", "_expmAction_RcppExport_validate", (DL_FUNC)_expmAction_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_expmAction_cpp_v_exp_Q_t", (DL_FUNC) &_expmAction_cpp_v_exp_Q_t, 4},
    {"_expmAction_RcppExport_registerCCallable", (DL_FUNC) &_expmAction_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_expmAction(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
