# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Evaluate matrix exponential action using uniformization
#' @param v A row vector
#' @param Q a sparse rate matrix
#' @param t Numeric time value, action evaluated is v'exp(Q*t)
#' @param tolerance Maximum error of the numeric calculation
#' @export
cpp_v_exp_Q_t <- function(v, Q, t = 1, tolerance = 1.0e-12) {
    .Call(`_expmAction_cpp_v_exp_Q_t`, v, Q, t, tolerance)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_expmAction_RcppExport_registerCCallable`)
})
