# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cpp_execute_uniformization_advanced <- function(Q, v, m, alpha, tolerance) {
    .Call(`_expmAction_cpp_execute_uniformization_advanced`, Q, v, m, alpha, tolerance)
}

#' @export
cpp_execute_uniformization_time <- function(Q, v, alpha_0, t, tolerance) {
    .Call(`_expmAction_cpp_execute_uniformization_time`, Q, v, alpha_0, t, tolerance)
}

rcpparma_hello_world <- function() {
    .Call(`_expmAction_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_expmAction_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_expmAction_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_expmAction_rcpparma_bothproducts`, x)
}

#' @export
cpp_tune_uniformization <- function(Q, tolerance = 1e-12) {
    .Call(`_expmAction_cpp_tune_uniformization`, Q, tolerance)
}

#' @export
cpp_execute_uniformization <- function(Q, x, s, m, alpha, tolerance = 1e-12) {
    .Call(`_expmAction_cpp_execute_uniformization`, Q, x, s, m, alpha, tolerance)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_expmAction_RcppExport_registerCCallable`)
})
